apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: shahmeetk/hello_dropwizard:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8081
          volumeMounts:
            - name: config-volume
              mountPath: /home/config
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 1
      volumes:
        - name: config-volume
          configMap:
            name: application-config
---
apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: application
